### ISSUE TITLE
Rotation issue

### ISSUE THREAD

**Issue by LucasCoelho** [brynbodayle/BABCropperView#10]
I'm Using BABCropperView (0.4.6). For some reason the photos I take with my device are falling into `case UIImageOrientationRight` thus being rotated by BAB Cropper

I don't fully understand what UIImageOrientation stands for and if this is expected.
I'd like to know if there is a way to disable the rotation of the image by the cropper or to correct (?) the orientation of my photo before cropping it

Thank you very much!

**Comment by brynbodayle** [comment]
@LucasCoelho Hmm, the iPhone camera's native orientation is landscape, so when you take portrait photos they have `UIImageOrientationRight`.

Are you having a particular issue? Is the sample project not working as expected on your device? Screenshots?

Thanks!

**Comment by LucasCoelho** [comment]
I'm sorry, my bad. Cropper is working great! 
I should not have created this issue
Thanks for the quick response

**Comment by brynbodayle** [comment]
@LucasCoelho No problem, glad it's working well for you.
