### ISSUE TITLE
Error with cocoapod beta 6

### ISSUE THREAD

**Issue by AlexeyBelezeko** [brynbodayle/BABCropperView#12]
Hi! I trying to build project with your pod. My cocopod version is 1.0 beta 6

I've got this error: 

error: /Users/alexey/Library/Developer/Xcode/DerivedData/Tipster-ghedtvicbrrnxbbbvlmlwydvyhet/Build/Products/Debug-iphonesimulator/BABCropperView/BABCropperView.bundle: No such file or directory

Can you delete bundle resources from podspec?

**Comment by brynbodayle** [comment]
Hmm, I wasn't getting the error, but I'm not using the 1.0.0 beta yet.

Please give it a try now with version 0.4.7
ee161fbaaf046d804ce8da60edc0a2b56be9fa37
