### ISSUE TITLE
When trying to crop image to a smaller size, image auto scales up to full width 

### ISSUE THREAD

**Issue by aliparlar** [brynbodayle/BABCropperView#13]
Hello,

When you pinch zoom out an image to a smaller size, the image autoscales back up to fill the entire width. In this case, user needs a third hand to keep the image pinched while tapping the crop button. Is it possible externally to modify this behaviour? 

Current behavior = image jumps back to match its width to crop area width

Proposed behaviour = image jumps back to fill width or height of the crop area, whichever is hit first. This way it would be easier for a user who for example wants to include the entire height of a portraid picture in a square

Is there an easy way to override this behaviour?

**Comment by brynbodayle** [comment]
Added a new property that will enable this behavior:

`    self.cropperView.allowsNegativeSpaceInCroppedImage = YES;
`

Let me know how it works for you.

**Comment by aliparlar** [comment]
Perfect! Thank you
