### ISSUE TITLE
Transparent image cropping problem.

### ISSUE THREAD

**Issue by ghouse1** [brynbodayle/BABCropperView#17]
When i try to crop a transparent image, this library is not working properly. it is making background black. please check with this testing image.
![eleptest](https://cloud.githubusercontent.com/assets/2462284/20462421/ee96a2d0-af2e-11e6-9de1-285ab2d7be32.png)

**Comment by brynbodayle** [comment]
Are you looking to leave the image background transparent? If so, you can do that by setting this property

````
imageCropperView. leavesUnfilledRegionsTransparent = YES
````
