### ISSUE TITLE
Full Image

### ISSUE THREAD

**Issue by hirenpanchal1608** [brynbodayle/BABCropperView#18]
I want to keep whole part of image.
Means no parts of image should be cropped.

if image is landscape image, then it should be converted into square image with black space on top and bottom

**Comment by brynbodayle** [comment]
Do you want to allow the user to zoom out when cropping the image? So increasing the amount of black space around the image?

**Comment by hirenpanchal1608** [comment]
Yea exactly

Right now If i want to keep original landscape image as it is but in square
instead of landscape, i can not do

**Comment by brynbodayle** [comment]
Ah, so you'll want to set `. allowsNegativeSpaceInCroppedImage = YES` on the cropper. But this will also allow them to zoom in on the photo. Currently the cropper doesn't support preventing the user from zooming in and just allowing them to zoom out.

**Comment by hirenpanchal1608** [comment]
Ohhh

By the way thank you for quick response.

This is very helpful library

**Comment by brynbodayle** [comment]
@hirenpanchal1608 Thanks!

I actually just pushed version 0.5.1 which exposes the internal UIImageView and UIScrollView used by the cropper view. So now you could actually achieve what you were looking to do by adjusting the minimum and maximum zoom scale properties on the UIScrollView and setting `. allowsNegativeSpaceInCroppedImage = YES`on the cropper.
