### ISSUE TITLE
Image quality loss after cropping

### ISSUE THREAD

**Issue by LucasCoelho** [brynbodayle/BABCropperView#2]
I'm losing a lot of the quality image using this code
Here are some before and after cropping
<img width="487" alt="original" src="https://cloud.githubusercontent.com/assets/2384916/10138026/3bf4fd04-65f4-11e5-8c13-0327f339cec9.png">
<img width="487" alt="aftercropping" src="https://cloud.githubusercontent.com/assets/2384916/10138027/3bfbbe96-65f4-11e5-9ad9-96f1e9f6140e.png">

Thanks

**Comment by brynbodayle** [comment]
Hi Lucas, can you post a before an after and the original size image you are testing with?

I can look into the issue.

Thanks!

**Comment by LucasCoelho** [comment]
Thanks for the quick reply! Done it.

**Comment by brynbodayle** [comment]
Thanks, I'lll take a look this weekend.

**Comment by brynbodayle** [comment]
@LucasCoelho give version 0.4.0 a try and let me know how it works for you.

**Comment by LucasCoelho** [comment]
Hi @brynbodayle, I'm still having the same issues

**Comment by brynbodayle** [comment]
Whoops, I think I made a mistake while versioning the CocoaPod. Try updating to 0.4.1 I just pushed.

**Comment by LucasCoelho** [comment]
@brynbodayle Still loosing quality

**Comment by brynbodayle** [comment]
@LucasCoelho Would you mind posting a few examples?

**Comment by LucasCoelho** [comment]
@brynbodayle I updated the issue with images using 0.4.1

**Comment by brynbodayle** [comment]
@LucasCoelho Hmm, what value are you passing in for the cropSize when you configure the cropper view?

I'm using 720x720 and I was able to get the results below. I don't believe there is any quality loss with them.

![screen shot 2015-09-28 at 9 24 31 am](https://cloud.githubusercontent.com/assets/1455522/10138163/c1f791c8-65c2-11e5-9498-603d4087363d.png)
![screen shot 2015-09-28 at 9 24 38 am](https://cloud.githubusercontent.com/assets/1455522/10138170/c61a0542-65c2-11e5-914c-8041439565e2.png)

**Comment by LucasCoelho** [comment]
let side = UIScreen.mainScreen().bounds.width
    cropperView.cropSize = CGSize(width: side, height: side)

**Comment by LucasCoelho** [comment]
You found the reason!

**Comment by brynbodayle** [comment]
@LucasCoelho Ah, that would be a problem. If you're outputting to the screen width screen scale is not being taken into account. So you're image will be between 320-375 pixels wide, whereas the screen is between 640-1125 pixels wide.
