### ISSUE TITLE
How to centre the image on load & scale to take up full screen

### ISSUE THREAD

**Issue by lxdyglt** [brynbodayle/BABCropperView#20]
Two Questions:

1. When image is loaded and if the image size is larger then the crop view size, I want to centre the image (currently the image scroll view is not auto scrolled to centre).

2. When image is loaded, I want the image scale to take up the entire phone Window (user can zoom in later if they want).

For question 2 I've tried to set "cropDisplayScale", "contentScaleFactor" & "scrollView.setZoomScale" but seems no luck.

**Comment by lxdyglt** [comment]
For Q2 I can set "scrollView.setZoomScale" on viewDidAppear, but not sure if this is the best way to do it.

**Comment by brynbodayle** [comment]
1. Will need to be added to BABCropperView, but it sounds like a sensible default behavior.
2. I believe this already works, can you post a screenshot or let me know your test scenario: what image size, crop size, and cropper view size is set.

**Comment by lxdyglt** [comment]
For Q2, it works by setting your "scrollView.setZoomScale" on viewDidAppear, please let me know if there is a better way.

**Comment by brynbodayle** [comment]
What crop size and what is the size of the image you're testing with?
