### ISSUE TITLE
discrepancy in - (void)updateScrollViewZoomScales

### ISSUE THREAD

**Issue by amit132** [brynbodayle/BABCropperView#23]
In updateScrollViewZoomScales method:

else { //landscape image
            
if((scrollViewHeight >= scrollViewWidth) || (self.cropSize.width/self.cropSize.height < imageViewWidth/imageViewHeight)) {
.....
}

The OR operator is used in else condition instead of AND as defined in if condition.

**Comment by brynbodayle** [comment]
Ah, thanks for finding this! Fixed here https://github.com/brynbodayle/BABCropperView/commit/b2904ed33b185ca249ec79f44f9e44abc4bbf61a
