### ISSUE TITLE
Unexpected cropping issues on real devices

### ISSUE THREAD

**Issue by siggb** [brynbodayle/BABCropperView#3]
Hello,
i have noticed that last changes have broken the project.
When i run example project on iPhone 6+ (iOS 9.0) and choose taken photos (with `imageOrientation == UIImageOrientationRight`) - there is always the same result: cropped photo not rotated and not cropped actually.
<img src="https://cloud.githubusercontent.com/assets/5582705/10245374/94c47216-690f-11e5-870b-6c2fa5172eb4.PNG" alt="Original Image" width="320" height="568" /><img src="https://cloud.githubusercontent.com/assets/5582705/10245346/435ddffc-690f-11e5-8cdd-fc4db7565e22.PNG" alt="Result Image" width="320" height="568" />

**Comment by brynbodayle** [comment]
@siggb Ah, I know the issue. Thanks!

Please try using version "0.3.2" for now and I'll get an update out soon.

**Comment by brynbodayle** [comment]
Thanks again for fixing this.
