### ISSUE TITLE
Cropping bug

### ISSUE THREAD

**Issue by kioltk** [brynbodayle/BABCropperView#5]
It looks like the bug with small pictures, however the pictures are not so small.. 

For example I use  default pictures from iOS simulator

<img width="487" alt="screen shot 2015-12-06 at 5 01 37 pm" src="https://cloud.githubusercontent.com/assets/5237220/11614027/c4e0c8bc-9c3d-11e5-94e5-7ae8e64317cb.png">
<img width="487" alt="screen shot 2015-12-06 at 5 01 41 pm" src="https://cloud.githubusercontent.com/assets/5237220/11614028/c4e71316-9c3d-11e5-904e-20b4025c377f.png">

Here is my code. The `view` is view of controller that is fullscreen size
```swift        
babCropper.cropSize = CGSizeMake(view.bounds.width, view.bounds.width * 1.2)
```

**Comment by kioltk** [comment]
Guys?

**Comment by brynbodayle** [comment]
Which version of this project are you using @kioltk ?

**Comment by kioltk** [comment]
@brynbodayle I am using the last one - 0.4.2
Just digging here and found out it happens cause of toolbar of navigation controller. Seems like here `cropFrameRect.origin.y = self.scrollView.bounds.origin.y + self.scrollView.contentInset.top;` we have to add the height of toolbar.
Can you try it? Cause I'm not so good in Objective-C

**Comment by kioltk** [comment]
up

**Comment by brynbodayle** [comment]
Hi @kioltk,

Sorry for the delay in response, I've been traveling.

I believe the solution you need is setting this property to false in the UIViewController that holds the BABCropperView.

`self.automaticallyAdjustsScrollViewInsets = NO;`

More information on that below:
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/occ/instp/UIViewController/automaticallyAdjustsScrollViewInsets

**Comment by kioltk** [comment]
Tried it. Did not help

**Comment by brynbodayle** [comment]
The difference between the two screenshots you've posted seems quite significant. Do you possibly have a video of the bug you can send?

**Comment by kioltk** [comment]
[Uploaded the video to dropbox](https://www.dropbox.com/s/x0ibqjmhmj6mfsm/cropping%20bug.mov?dl=0). 
Do you see the flower and the borders? I put the flower inside the border, then I crop and in the output I have a flower that kinda cropped at bottom, and unnecessary space added in the top.

**Comment by kioltk** [comment]
up

**Comment by brynbodayle** [comment]
@kioltk Try version 0.4.4 for a fix. There were some issues with the default image orientation case in a fix that @siggb pushed.

**Comment by kioltk** [comment]
Weeeell, it's work now. Thanks.

**Comment by brynbodayle** [comment]
@kioltk I would also recommend taking into account the device resolution when setting your crop size. For instance:

```
CGFloat scale = [UIScreen mainScreen].scale;
babCropper.cropSize = CGSizeMake(view.bounds.width * scale, view.bounds.width * 1.2 * scale)
```
