### ISSUE TITLE
Get CGRect of cropping rectangle

### ISSUE THREAD

**Issue by xergic** [brynbodayle/BABCropperView#6]
It would be really great if there was *property* to get CGRect of cropping rectangle, like 'UIImagePickerControllerCropRect' key in *UIImagePickerControllerDelegate* protocol:

> Specifies the cropping rectangle that was applied to the original image.
> The value for this key is an NSValue object containing a CGRect opaque type.

Or any suggestion how to get it would be appreciated. Great library btw, saved me a lot of time.

**Comment by brynbodayle** [comment]
Thanks for the feedback @xergic. I've gone ahead and added this crop rect to the completion block for the crop image method. Let me know how this works for you.

**Comment by xergic** [comment]
Works great! Thanks a lot.
