### ISSUE TITLE
No tags in this repo causing error in CocoaPods: "Could not find remote branch 0.4.5 to clone"

### ISSUE THREAD

**Issue by NicholasTD07** [brynbodayle/BABCropperView#9]
I checked that there's no tag or release on GitHub, https://github.com/brynbodayle/BABCropperView/releases, and I think that's why `pod install` is falling because it can't find that tag while trying to clone the repo at that tag.

To fix it, I think you need to push your tags onto GitHub by running this in your terminal
```sh
git push --tags
```

Podfile:
```rb
pod 'BABCropperView', '~> 0.4.5'
```

Log:
```sh
> pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing BABCropperView (0.4.5)

[!] Error installing BABCropperView
[!] /usr/local/bin/git clone https://github.com/brynbodayle/BABCropperView.git /var/folders/9x/zk40rlgn7sqc5rl6rl_qjs1h0000gn/T/d20160121-8474-1879es3 --single-branch --depth 1 --branch 0.4.5

Cloning into '/var/folders/9x/zk40rlgn7sqc5rl6rl_qjs1h0000gn/T/d20160121-8474-1879es3'...
warning: Could not find remote branch 0.4.5 to clone.
fatal: Remote branch 0.4.5 not found in upstream origin
```

My temporary workaround is to specify a commit in Podfile rather than a tag for BABCropperView.
```rb
pod 'BABCropperView', :git => 'https://github.com/brynbodayle/BABCropperView.git', :commit => 'af6c17a'
```

PS.

Great work! Thanks for your effort for making this lovely framework!

**Comment by brynbodayle** [comment]
Ah, just pushed the tags. Let me know if that works.

Thanks for finding and reporting this!
